config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'urls#index'
  resources :urls
  get '/urls/:id/short' => 'urls#short'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :long_url, uniqueness: true
  before_save :shorten

  def shorten
    self.short_url = SecureRandom.hex(3)
  end

  def increase
    self.count  += 1
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
  end

  def show
    @url = Url.find(params[:id])
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    @url.shorten
    if @url.save
        redirect_to @url
    else
        render 'new'
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy
    redirect_to urls_path
  end

  def short
    url = Url.find(params[:id])
    redirect_to url.long_url
  end 

  private
  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
  <p>
    <%= f.label "Type your URL here:" %><br>
    <%= f.text_field :long_url %>
  </p>

  <p>
    <%= f.submit "Shorten URL!" %>
  </p>
    <% end %>

app/views/urls/index.html.erb
<table>
<tr>
<th>Original URL</th>
<th>Shortened URL</th>
</tr>

<%  @urls.each do |url| %>
    <tr>
    <td> <a href = <%= url.long_url %> ><%= url.long_url %></a></td>
    <td> <%= link_to url.short_url, controller: :urls, action: :short, id: url %></a> </td>
    <td> <%= link_to 'Show', url_path(url) %> </td>
    <td><%= link_to 'Delete', url_path(url), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

<%= link_to "Shorten a Url!", new_url_path %>

app/views/urls/new.html.erb
<h3>This is urls/new</h3>
<%= render 'form' %>
<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<h3>This is urls/show</h3>
  <p><%= @url.long_url %></p>
  <p><%= @url.short_url %></p>
  <%= link_to 'Back', urls_path %>